---
# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
  - package-ecosystem: poetry
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    versioning-strategy: increase
